name: First pipline

on:
  push:
    branches: ["main"]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP with PECL extension
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: imagick, swoole
      - uses: actions/checkout@v3
      - name: Copy .env
        run: cp .env.ci .env
      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress
      - name: Generate key
        run: php artisan generate:key
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Run Test
        run: php artisan test
      # - name: phpstan
      #   run: ./vendor/bin/phpstan analyse --memory-limit=1G
